# Etude d'un système planétaire
 
**Lehanneur Iona - Blasco Anaïs - Daumont Jean-Baptiste**
*ARE DYNAMIC - 2021*

## Préambule

Un système planétaire tout comme celui dans lequel nous évoluons, se compose de corps célestes (astéroïdes, comètes…). Tous gravitent autour d’une étoile centrale.
Ce projet de recherche documentaire a pour objectif de déterminer de quelle manière des facteurs tels que la taille d’un système complet, la masse et le diamètre de l’étoile centrale et le nombre de planètes influent sur les différentes trajectoires des corps célestes.
Pour ce faire, nous utiliserons différentes métriques via le langage de programmation Python dans le but de comparer différents systèmes modélisés par nos soins. Nous en déduirons à partir de quelle masse, l’astre central est trop « léger » pour attirer les corps et inversement, à partir de quelle masse et taille se trouve-t-il trop « gros » pour que les planètes n’entrent pas en collision avec ce dernier.

La taille et le nombre de planètes ont aussi un rôle essentiel à jouer, nos hypothèses soutiennent qu’un système trop grand comparé à la taille de l’étoile, empêchera les planètes lointaines d’engendrer une orbite stable, ainsi, les plus éloignées ne feront plus partie du système étudié.
En somme, nous conclurons avec des courbes significatives, montrant le comportement des astres quant à la modification des paramètres cités précédemment, ce qui constituera la réponse à notre problématique.


## Objectifs

Dans ce notebook nous allons essayer de modéliser les trajectoires des planètes avec l'aide de formules mathématiques concrètes, afin que notre modèle mette en lumière les différences d'un système à l'autre. Nous allons essayer de comprendre les différentes façons d'implémenter un modèle significatif, et d'obtenir des résultats commentés qui permettront de comprendre dans quelles mesures un système va-t-il émerger, et sous quelle(s) condition(s) va-t-il pouvoir accueillir un nombre de planètes plus élevé que le notre.



#  Etude du modèle en deux dimensions

**Objectifs : implémenter le modèle planétaire en python, le tester sur un exemple simple puis étudier l'impact que peuvent avoir les paramètres du modèle sur le système.**

Nous allons étudier l’impact des paramètres du modèle : 
- la taille du système,
- le nombre de planètes,
- le diamètre de l'étoile,
- la masse de l'étoile,

**Pour quantifier l'impact de ces paramètres, en plus de l'observation visuelle de l'évolution de notre système, nous utiliserons les métriques suivantes :**


In [1]:
import numpy as np

import random

from matplotlib import pyplot as plt

In [2]:
# Paramètres du modèle Planétaire
sysize = 11     # Taille du système
plannum= 5     # Nombre de planètes (pour planet number à l'anglaise évidemment)
diameter=3    # Diamètre de l'étoile centrale en kms
mass=2       # Mass de l'étoile centrale

**Notre système est composé d'une matrice carrée de taille sysize.**

In [3]:
system=np.zeros((sysize,sysize),dtype=int)
print (system)

[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


**la fonction ```print_system``` permet d'afficher le système.**


In [18]:
def print_system(system):
    result = ""
    for i in system:
        for j in i:
            result += "|"+str(j)
        result += "|"+'\n'
    return result
print(print_system(system))

|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|1|1|1|0|0|0|0|
|0|0|0|0|1|1|1|0|0|0|0|
|0|0|0|0|1|1|1|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|0|0|0|0|0|



**Notre étoile centrale est donc située au entre du système (ici matrice), elle est représentée grâce à ses coordonnées.**

In [5]:
coord_star = sysize//2

**La fonction ```create_etoile```place l'étoile au centre du système selon ses coordonnées.**

In [6]:
def create_etoile(system):
    
    system[coord_star-diameter//2:coord_star+diameter//2+1, coord_star-diameter//2:coord_star+diameter//2+1] = 1

In [7]:
create_etoile(system)

**La fonction ``rand_plan`` permet de créer les planète de notre système en fonction de *plannum*, et de leur prodiguer une masse random dans un intervalle réliste (la planète ne peut être plus lourde que l'étoile centrale), ainsi qu'un diamètre plausible (même raisonnemet)**

In [9]:
def rand_plan(plannum):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-9-03ab696e4839>, line 2)